// Link manifest (spec §3.2). Plaintext never leaves the client;
// manifest_enc = XChaCha20-Poly1305(channel_key, random nonce || ciphertext).

import { xchacha20poly1305 } from '@noble/ciphers/chacha';
import { concatBytes } from './hash.js';
import { MANIFEST_VERSION, CHUNKER_VERSION } from './constants.js';

export interface ManifestChunk {
  blob_id: string; // hex BLAKE3-256 of ciphertext
  key: string; // b64 32-byte chunk key
  nonce: string; // b64 24-byte nonce
  size: number; // ciphertext size in bytes
  cap?: string; // server-issued capability (presigned URL) — refreshed via API
}

export interface Manifest {
  v: number;
  kind: 'file' | 'text';
  name: string;
  /** A user-chosen display title, renameable at any time. `name` stays the
   *  original filename so downloads keep it; absence means "show the default"
   *  (the filename, or the text-item label). */
  title?: string;
  /** Stable source asset id when a platform can provide one. Web does not set
   *  it, but preserves values written by native clients. */
  asset_id?: string;
  /** The SENDING device classified this note's text and judged it to hold a
   *  credential. Written by iOS 2.1(22) and later; web does not write it yet.
   *
   *  Only ever `true` or absent — no client writes `false`. Absent means "the
   *  sender did not classify, or found nothing", which is not the same as
   *  safe, so nothing in the UI may call an unmarked note safe. Receivers act
   *  on `=== true` alone and render everything else normally.
   *
   *  Advisory UX — a cover against someone reading over your shoulder — not a
   *  security boundary: a tap always reveals. It rides inside the sealed
   *  manifest on purpose and must never be copied into an unsealed document,
   *  API body, log or analytics event, since a plaintext copy would tell the
   *  server exactly which notes hold credentials. */
  sensitive?: boolean;
  mime: string;
  size: number;
  created_at: string;
  chunker?: string;
  text?: string;
  /** Sanitized HTML for text items that carry formatting. `text` always holds
   *  the plain rendering, so a client that ignores this field still works. */
  html?: string;
  chunks: ManifestChunk[];
  /** A JPEG data URI for images and video. Carried inside the manifest rather
   *  than as its own content-addressed blob: a separate thumbnail would be a
   *  second, smaller, separately claim-counted object derived from the same
   *  photo, which is exactly the correlation surface §5.7 is trying to keep
   *  narrow. The manifest is per-link and never deduplicated. */
  thumb_data?: string;
  /** Open-graph preview for a pasted link, image inlined as a data URI so
   *  rendering it contacts nobody. Generated by the one server endpoint that
   *  sees content; see functions/src/unfurl.ts for why that is unavoidable. */
  link_preview?: {
    url: string;
    title?: string;
    description?: string;
    site?: string;
    image?: string;
  };
  thumb?: { blob_id: string; key: string; nonce: string };
  /** Set while the item has a public share. The key is kept here — inside the
   *  manifest, which only the owner's devices can open — because the server
   *  never holds it and the URL fragment is gone the moment the dialog closes.
   *  Without this the owner could not copy their own link a second time.
   *  `bar` mirrors the share row's burn-after-read flag so a device that has
   *  not heard from the shares listener still reopens the dialog red; the
   *  live row wins whenever both are in hand. */
  share?: { id: string; key: string; bar?: boolean };
  /** Present when the item is a code snippet. `auto` records whether the
   *  language was detected or chosen, so a user's correction is never
   *  overwritten by a later guess. */
  code?: { lang: string; auto?: boolean };
}

export function newManifest(partial: Omit<Manifest, 'v' | 'chunker'>): Manifest {
  return { v: MANIFEST_VERSION, chunker: CHUNKER_VERSION, ...partial };
}

// ---- versioned envelope ----
//
// The key version cannot live inside the ciphertext: you would need the key to
// read it, and the key is what it identifies. So it rides in front, in the
// clear. It reveals nothing — a small integer that is the same for everyone on
// a given key generation — and it makes the account key rotatable: a manifest
// sealed under an older generation still says which one it needs.
//
//   versioned:  'Z' | version | nonce(24) | ciphertext
//   legacy v1:              nonce(24) | ciphertext
//
// Legacy bytes have no marker, so they are recognised by elimination. A random
// nonce beginning with 'Z' is caught by the AEAD tag failing, and the caller
// falls back — which `openSealed` does automatically.
const ENVELOPE_MAGIC = 0x5a; // 'Z'
export const KEY_VERSION_LEGACY = 1;

/** Which key generation sealed these bytes. Readable without any key, which is
 *  the whole point — the client uses it to fetch the right one. */
export function envelopeVersion(sealed: Uint8Array): number {
  if (sealed.length > 26 && sealed[0] === ENVELOPE_MAGIC && sealed[1] >= 1) return sealed[1];
  return KEY_VERSION_LEGACY;
}

function sealBytes(key: Uint8Array, version: number, plain: Uint8Array): Uint8Array {
  if (version < 1 || version > 255) throw new Error('key version out of range');
  const nonce = new Uint8Array(24);
  crypto.getRandomValues(nonce);
  const ct = xchacha20poly1305(key, nonce).encrypt(plain);
  return concatBytes(new Uint8Array([ENVELOPE_MAGIC, version]), nonce, ct);
}

function openSealed(key: Uint8Array, sealed: Uint8Array): Uint8Array {
  const versioned = envelopeVersion(sealed) !== KEY_VERSION_LEGACY || sealed[0] === ENVELOPE_MAGIC;
  if (versioned && sealed.length > 26) {
    try {
      return xchacha20poly1305(key, sealed.slice(2, 26)).decrypt(sealed.slice(26));
    } catch {
      // Fall through: a legacy nonce that happens to start with 'Z'.
    }
  }
  return xchacha20poly1305(key, sealed.slice(0, 24)).decrypt(sealed.slice(24));
}

/** Raw envelope seal/open for non-manifest payloads (e.g. wrapped channel keys). */
export const sealRaw = sealBytes;
export const openRaw = openSealed;

export function sealManifest(channelKey: Uint8Array, manifest: Manifest, version = KEY_VERSION_LEGACY): Uint8Array {
  return sealBytes(channelKey, version, new TextEncoder().encode(JSON.stringify(manifest)));
}

export function openManifest(channelKey: Uint8Array, sealed: Uint8Array): Manifest {
  const m = JSON.parse(new TextDecoder().decode(openSealed(channelKey, sealed))) as Manifest;
  // `chunks` is required by the type and guaranteed by nothing. These bytes were
  // written by whoever sealed them — an older build, or the iOS/Android client
  // writing into a shared channel — so the cast above is an assertion about
  // someone else's JSON. Supply the field here, at the one place stored bytes
  // become a Manifest, rather than at each of the five callers that walk it.
  //
  // An empty array is the honest value and not a fallback: a note has no chunks
  // and never did. It also keeps delete working on a row that is already wrong,
  // which is the failure that matters — `caps: []` is what deleteUnreadable and
  // account deletion already send for a manifest they cannot read.
  if (!Array.isArray(m.chunks)) m.chunks = [];
  return m;
}

export function encryptChannelName(channelKey: Uint8Array, name: string, version = KEY_VERSION_LEGACY): Uint8Array {
  return sealBytes(channelKey, version, new TextEncoder().encode(name));
}

export function decryptChannelName(channelKey: Uint8Array, sealed: Uint8Array): string {
  return new TextDecoder().decode(openSealed(channelKey, sealed));
}
